store/cart/urls.py
from django.urls import path
from .import views

app_name ='cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),

]

store/shop_counter/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.product_list,name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<slug:category_slug>/<slug:sub_category_slug>', views.product_list, name='product_list_by_subcategory'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('shop_counter.urls')),
    path('account/', include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/shop_counter/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=25)
    slug = models.SlugField(max_length=25, unique=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class SubCategory(models.Model):
    category = models.ForeignKey(Category, related_name='sub_categories', on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=25, unique=True)
    slug = models.SlugField(max_length=25, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_sub_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, null=True, blank=True)
    sub_category = models.ForeignKey(SubCategory, related_name='product', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='img', null=True, blank=True)
    description = models.TextField(null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

store/shop_counter/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None, sub_category_slug=None):
    category = None
    sub_categories = None
    sub_category = None
    check = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        sub_categories = SubCategory.objects.filter(category=category)
        products = products.filter(category=category)
    if sub_category_slug:
        sub_category = get_object_or_404(SubCategory, slug=sub_category_slug)
        products = Product.objects.filter(sub_category=sub_category)
        check = 1

    return render(request, 'shop_counter/product/list.html', locals())


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop_counter/product/detail.html', locals())

store/shop_counter/templates/shop_counter/product/detail.html
{% extends 'shop_counter/base.html' %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}


{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %} {{ product.image.url }}
        {% else %} {% static 'img/no_image.png' %} {% endif %}">
        <h1>{{ product.name }}</h1>
        <h2>
            <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a><br>
            <a href="#">{{ product.sub_category }}</a>
        </h2>
        <p class="price">${{ product.price }}</p>
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {% csrf_token %}
                {{ cart_product_form }}
                <input type="submit" value="Add to cart">
            </form>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

store/shop_counter/templates/shop_counter/product/list.html
{% extends 'shop_counter/base.html' %}
{% load static %}
    {% block title %}
    {% if category %}
        {{ category.name }}
    {% else %}Products
    {% endif %}
    {% endblock %}

{% block content %}
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url 'shop:product_list' %}">All</a>
            </li>
                {% for c in categories %}

                    <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">

        {% if category and sub_category %}
            <h1>{{ category.name }}</h1><br>
            <h2>{{ sub_category.name }}</h2>
                {% for product in products %}
                        <div class="item">
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %}{{ product.image.url }}
                                {% else %}{% static 'img/no_image.png' %}{% endif %}">
                            </a>
                            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                            <br>
                            ${{ product.price }}
                        </div>
                {% endfor %}


            {% elif category %}
                <h1>{{ category.name }}</h1>
                {% if check is None %}
                    {% for sub_category in sub_categories  %}
            <br><a href="{% url 'shop:product_list_by_subcategory' category.slug sub_category.slug %}"><h2>{{ sub_category.name }}</h2></a>
                    {% endfor %}
                {% endif %}


            {% else %}<h1>Products</h1>
                 {% for product in products %}
                    <div class="item">
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %}{{ product.image.url }}
                            {% else %}{% static 'img/no_image.png' %}{% endif %}">
                        </a>
                        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                        <br>
                        ${{ product.price }}
                    </div>
                {% endfor %}
            {% endif %}

    </div>
{% endblock %}