store/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.create_user, name='create_user'),
    path('signup/verify/', views.verify, name='verify'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('edit/', views.edit, name='edit')
]

store/cart/urls.py
from django.urls import path
from .import views

app_name ='cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),

]

store/shop_counter/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.product_list,name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<slug:category_slug>/<slug:sub_category_slug>', views.product_list, name='product_list_by_subcategory'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('shop_counter.urls')),
    path('account/', include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/shop_counter/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=25)
    slug = models.SlugField(max_length=25, unique=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class SubCategory(models.Model):
    category = models.ForeignKey(Category, related_name='sub_categories', on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=25, unique=True)
    slug = models.SlugField(max_length=25, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_sub_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, null=True, blank=True)
    sub_category = models.ForeignKey(SubCategory, related_name='product', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='img', null=True, blank=True)
    description = models.TextField(null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

store/shop_counter/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None, sub_category_slug=None):
    category = None
    sub_categories = None
    sub_category = None
    check = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        sub_categories = SubCategory.objects.filter(category=category)
        products = products.filter(category=category)
    if sub_category_slug:
        sub_category = get_object_or_404(SubCategory, slug=sub_category_slug)
        products = Product.objects.filter(sub_category=sub_category)
        check = 1

    return render(request, 'shop_counter/product/list.html', locals())


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop_counter/product/detail.html', locals())

store/shop_counter/templates/shop_counter/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}My Shop{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
</head>
<body>
    <div id="header">
        <a href="/" class="logo">My shop</a>
    </div>
    <div id="subheader">
        {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                Your cart:
                <a href="{% url 'cart:cart_detail' %}">
                    {{ total_items }} item{{ total_item|pluralize }},
                    ${{ cart.get_total_price }}
                </a>
            {% else %}
                Your cart is empty.
            {% endif %}
        {% endwith %}
        {% if user.is_authenticated %}
        {{ user.username }}   |  <a href="{% url 'accounts:logout' %}">Logout</a>|
        <a href="{% url 'accounts:edit' %}">Edit Profile</a>
        {% else %}
            <a href="{% url 'accounts:create_user' %}">Signup | </a>
            <a href="{% url 'accounts:login' %}">Log-in</a>
        {% endif %}
    </div>

        {% block content %} {% endblock %}

</body>
</html>